import { useEffect } from 'react';
import { Link } from 'react-router-dom';

function App2PrivacyPolicy() {
  useEffect(() => {
    document.title = 'TOEFL® 1001';
    
    // Change favicon to TOEFL icon
    const link = document.querySelector("link[rel~='icon']") as HTMLLinkElement;
    if (link) {
      link.href = '/TOEFL1001.png';
    } else {
      const newLink = document.createElement('link');
      newLink.rel = 'icon';
      newLink.type = 'image/png';
      newLink.href = '/TOEFL1001.png';
      document.head.appendChild(newLink);
    }
    
    // Cleanup: restore default favicon when component unmounts
    return () => {
      const defaultLink = document.querySelector("link[rel~='icon']") as HTMLLinkElement;
      if (defaultLink) {
        defaultLink.href = '/ViralRecipes.png';
      }
    };
  }, []);
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-white shadow-sm sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <Link to="/TOEFL1001" className="flex items-center space-x-3">
              <img src="/TOEFL1001.png" alt="TOEFL® 1001" className="w-10 h-10 rounded-xl" />
              <span className="text-2xl font-bold text-gray-900">TOEFL® 1001</span>
            </Link>
            <Link 
              to="/TOEFL1001"
              className="px-6 py-2 rounded-full text-white font-medium transition-colors" 
              style={{backgroundColor: '#8E44AD'}} 
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#6A3480'} 
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#8E44AD'}
            >
              Back to Home
            </Link>
          </div>
        </div>
      </header>

      {/* Privacy Policy Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="prose prose-lg max-w-none">
          <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
          
          <div className="space-y-6 text-gray-700 leading-relaxed">
            <div className="bg-gray-50 p-6 rounded-lg">
              <p><strong>Effective Date:</strong> [November 28, 2025]</p>
            </div>

            <p>TOEFL® 1001 – Flashcards ("App") respects your privacy. This Privacy Policy explains how we handle your information.</p>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Information Collected</h2>
              <p>The App does not require user registration or login. All data, including flashcard progress and bookmarks, is stored locally on your device.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Subscription Data</h2>
              <p>Any subscription information is managed exclusively through the Apple App Store. The App does not access or store your payment information.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">No Personal Information Sharing</h2>
              <p>Since all user data is stored locally on the device, we do not collect, share, or sell personal information.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Third-Party Services</h2>
              <p>The App may use Apple services for subscription management. Apple's privacy policy governs any information processed through their platform.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Disclaimer</h2>
              <p>All words, example sentences, and pronunciations are generated by AI. The App does not guarantee TOEFL score improvement. Score examples are for illustrative purposes only.</p>
              <p className="mt-2">TOEFL® is a registered trademark of ETS. This App is not affiliated with, endorsed, or approved by ETS.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to Privacy Policy</h2>
              <p>We may update this Privacy Policy at any time. Continued use of the App indicates acceptance of any changes.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact</h2>
              <p>For questions regarding these Terms or Privacy Policy, please contact:</p>
              <p className="bg-purple-50 p-4 rounded-lg inline-block mt-2">
                📧 <a href="mailto:appsutk@gmail.com" className="text-purple-600 hover:text-purple-800 font-medium">appsutk@gmail.com</a>
              </p>
            </div>
          </div>

          <div className="text-center mt-12">
            <Link 
              to="/TOEFL1001"
              className="inline-flex items-center px-6 py-3 rounded-full text-white font-medium transition-colors"
              style={{backgroundColor: '#8E44AD'}} 
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#6A3480'} 
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#8E44AD'}
            >
              ← Back to Home
            </Link>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center space-y-4">
            <div className="flex items-center justify-center space-x-3">
              <img src="/TOEFL1001.png" alt="TOEFL® 1001" className="w-8 h-8 rounded-lg" />
              <span className="text-xl font-bold">TOEFL® 1001</span>
            </div>
            <p className="text-gray-400 max-w-md mx-auto">
              The fastest, simplest, and most effective way to master TOEFL vocabulary. Prepare for the 2026 TOEFL® New Format with 1001 essential words.
            </p>
          </div>

          <div className="border-t border-gray-800 mt-12 pt-8">
            <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
              <p className="text-gray-400">© 2025 TOEFL® 1001. All rights reserved.</p>
              <div className="flex space-x-6">
                <Link to="/TOEFL1001/privacy-policy" className="text-gray-400 hover:text-white transition-colors text-sm">Privacy Policy</Link>
                <Link to="/TOEFL1001/terms-of-use" className="text-gray-400 hover:text-white transition-colors text-sm">Terms & Conditions</Link>
                <a href="/TOEFL1001#faq" className="text-gray-400 hover:text-white transition-colors text-sm">FAQ</a>
                <a href="mailto:appsutk@gmail.com" className="text-gray-400 hover:text-white transition-colors text-sm">Support</a>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App2PrivacyPolicy;

