import { useEffect } from 'react';
import { Link } from 'react-router-dom';

function App2TermsOfUse() {
  useEffect(() => {
    document.title = 'TOEFL® 1001';
    
    // Change favicon to TOEFL icon
    const link = document.querySelector("link[rel~='icon']") as HTMLLinkElement;
    if (link) {
      link.href = '/TOEFL1001.png';
    } else {
      const newLink = document.createElement('link');
      newLink.rel = 'icon';
      newLink.type = 'image/png';
      newLink.href = '/TOEFL1001.png';
      document.head.appendChild(newLink);
    }
    
    // Cleanup: restore default favicon when component unmounts
    return () => {
      const defaultLink = document.querySelector("link[rel~='icon']") as HTMLLinkElement;
      if (defaultLink) {
        defaultLink.href = '/ViralRecipes.png';
      }
    };
  }, []);
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-white shadow-sm sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <Link to="/TOEFL1001" className="flex items-center space-x-3">
              <img src="/TOEFL1001.png" alt="TOEFL® 1001" className="w-10 h-10 rounded-xl" />
              <span className="text-2xl font-bold text-gray-900">TOEFL® 1001</span>
            </Link>
            <Link 
              to="/TOEFL1001"
              className="px-6 py-2 rounded-full text-white font-medium transition-colors" 
              style={{backgroundColor: '#8E44AD'}} 
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#6A3480'} 
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#8E44AD'}
            >
              Back to Home
            </Link>
          </div>
        </div>
      </header>

      {/* Terms & Conditions Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="prose prose-lg max-w-none">
                <h1 className="text-4xl font-bold text-gray-900 mb-8">Terms of Use</h1>
          
          <div className="space-y-6 text-gray-700 leading-relaxed">
            <div className="bg-gray-50 p-6 rounded-lg">
              <p><strong>Effective Date:</strong> [November 28, 2025]</p>
            </div>

            <p>Welcome to TOEFL® 1001 – Flashcards (the "App"). By using this App, you agree to the following terms:</p>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">App Usage</h2>
              <p>The App provides flashcard-based vocabulary practice for TOEFL® preparation. All words, descriptions, examples, and pronunciations in the App are generated by AI. The App is intended for educational purposes only.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">No Guarantee of TOEFL® Score Increase</h2>
              <p>The App does not guarantee any increase in your TOEFL® score. Any score improvement examples provided are for illustrative purposes only and are not a promise or guarantee of results.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Subscription and Payments</h2>
              <p>The App may include subscription-based features. All subscriptions are handled and processed through the Apple App Store. You agree that the App does not manage payments directly, and all billing and subscription management are subject to Apple's terms.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Disclaimer</h2>
              <p>TOEFL® is a registered trademark of ETS. This App is not affiliated with, endorsed, or approved by ETS.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Limitation of Liability</h2>
              <p>The App and its content are provided "as is" without warranties of any kind. In no event shall the App or its developers be liable for any damages arising from the use of the App or the inability to achieve a specific TOEFL score.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Modifications</h2>
              <p>We may update these Terms of Use at any time. Your continued use of the App after changes constitutes your acceptance of the revised terms.</p>
            </div>
          </div>

          <div className="text-center mt-12">
            <Link 
              to="/TOEFL1001"
              className="inline-flex items-center px-6 py-3 rounded-full text-white font-medium transition-colors"
              style={{backgroundColor: '#8E44AD'}} 
              onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#6A3480'} 
              onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#8E44AD'}
            >
              ← Back to Home
            </Link>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center space-y-4">
            <div className="flex items-center justify-center space-x-3">
              <img src="/TOEFL1001.png" alt="TOEFL® 1001" className="w-8 h-8 rounded-lg" />
              <span className="text-xl font-bold">TOEFL® 1001</span>
            </div>
            <p className="text-gray-400 max-w-md mx-auto">
              The fastest, simplest, and most effective way to master TOEFL vocabulary. Prepare for the 2026 TOEFL® New Format with 1001 essential words.
            </p>
          </div>

          <div className="border-t border-gray-800 mt-12 pt-8">
            <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
              <p className="text-gray-400">© 2025 TOEFL® 1001. All rights reserved.</p>
              <div className="flex space-x-6">
                <Link to="/TOEFL1001/privacy-policy" className="text-gray-400 hover:text-white transition-colors text-sm">Privacy Policy</Link>
                <Link to="/TOEFL1001/terms-of-use" className="text-gray-400 hover:text-white transition-colors text-sm">Terms & Conditions</Link>
                <a href="/TOEFL1001#faq" className="text-gray-400 hover:text-white transition-colors text-sm">FAQ</a>
                <a href="mailto:appsutk@gmail.com" className="text-gray-400 hover:text-white transition-colors text-sm">Support</a>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App2TermsOfUse;

